fixtures:
    repositories:
      stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      powershell: 'https://github.com/puppetlabs/puppetlabs-powershell.git'
      windowsfeature: 'https://github.com/voxpupuli/puppet-windowsfeature.git'
    symlinks:
      wsusserver: "#{source_dir}"
