# This file can be used to customize the files managed by PDK.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator

Rakefile:
  requires:
    - 'puppet-strings/tasks'

.gitlab-ci.yml:
  delete: true

appveyor.yml:
  delete: true
  
.travis.yml:
  delete: true

.github/workflows/auto_release.yml:
  unmanaged: false

.github/workflows/release.yml:
  unmanaged: false

.github/workflows/pr_test.yml:
  unmanaged: false

.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false

